### ISSUE TITLE
building

### ISSUE THREAD

**Issue by tkone2018** [fongyk/RankWithRetrieval#1]
thanks for your codes. can you share the building train and evaluate steps ?thanks

**Comment by tkone2018** [comment]
@fongyk 您好！我运行dataset.py文件是出现错误：
 q_data = [e.strip() for e in f('{}/{}'.format(gt_path, f))]
TypeError: 'numpy.str_' object is not callable
您这边又出现这个错误吗？谢谢！

**Comment by fongyk** [comment]
你好，这个错误我没有遇见过，你这里是否有拼写错误: **f**('{}/{}'.format(gt_path, **f**)) 这里出现了两个**f**。python 2.x前面的f应该用file()，python 3.x用open()。
另外关于train和evaluate，在train.py里面应该都有。

**Comment by fongyk** [comment]
@tkone2018 你好，这个错误我没有遇见过，你这里是否有拼写错误: f('{}/{}'.format(gt_path, f)) 这里出现了两个f。python 2.x前面的f应该用file()，python 3.x用open()。
另外关于train和evaluate，在train.py里面应该都有。

**Comment by tkone2018** [comment]
@fongyk 好的，谢谢!

**Comment by tkone2018** [comment]
@fongyk 关于train.txt文件问题，我这边生成的train.txt文件内容是我目录下的文件，这应该没啥用，我已经生成了train_oxf.txt和train_par.txt文件，难道是将这两个文件合并在train.txt中吗？

**Comment by fongyk** [comment]
@tkone2018 这个是我没有说清楚。train.txt保存的是训练集各类别图像的路径，默认是用landmark_clean作训练集；而train_oxf.txt和train_par.txt分别是用paris6k和oxford5k作为训练集，然后在oxford5k和paris6k交叉测试。

**Comment by tkone2018** [comment]
@好的，谢谢！想问一下buildtestdata( )这个模块
       self.img_path = img_path
        self.gt_path = gt_path
        self.eval_func = eval_func
这三个参数分别代表什么啊，谢谢!

**Comment by tkone2018** [comment]
@fongyk 希望您在有空的时间完善一下readme文档，十分感谢！

**Comment by fongyk** [comment]
@tkone2018  关于readme文档这个确实不好意思，没认真写，我当时想着这个代码主要是面向image retrieval，这个buildtestdata是检索用的公开测试集oxford5k和paris6k的设置，所以相关方向的同学应该会懂这个。img_path是测试图像的目录，gt_path是ground_truth的目录，eval_func是测试代码的c++编译文件目录。如果你是用自己的测试集的话，就没必要用到这个。

**Comment by tkone2018** [comment]
@fongyk 好的，谢谢！
